config/routes.rb
Rails.application.routes.draw do
  resources :time_tracks do
    collection do
      get '(:date)', action: :index, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, as: :events_date
      post :start, action: :start
    end
    get :duplicate, action: :duplicate
    get :stop, action: :stop
  end
  resources :report, only: [:index] do
    collection do
      get '(:date)', action: :index, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, as: :report_date
    end
  end
  resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_track.rb
class TimeTrack < ApplicationRecord
  scope :date, ->(date = Time.zone.now.beginning_of_day.utc) { where('date(start_at) = :date', date: date.to_date) }
  scope :between, lambda { |date_range|
    time_track = TimeTrack.arel_table
    where(time_track[:start_at].between(date_range))
  }
end

app/controllers/application_controller.rb
require 'bootstrap-icons-helper'
class ApplicationController < ActionController::Base
  include BootstrapIconsHelper
end

app/controllers/report_controller.rb
# frozen_string_literal: true

class ReportController < ApplicationController
  def index
    @date = params[:date] && Time.zone.parse(params[:date]) || Time.zone.now
    start_date = @date.beginning_of_month.utc
    end_date = @date.end_of_month.utc
    @time_tracks = TimeTrack.between(start_date..end_date).all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @start_at = start_date
    @end_at = end_date
    @q = params[:q] || ''

    @time_tracks = results

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  private

  def results
    TimeTrack
      .between(@start_at..@end_at)
      .where('description LIKE ?', "%#{@q}%")
      .all
  end

  def start_date
    params[:start_at] && Time.zone.parse(params[:start_at]).utc ||
      params[:end_at] && (Time.zone.parse(params[:end_at]) - 1.month).utc ||
      Time.zone.now.beginning_of_month.utc
  end

  def end_date
    params[:end_at] && Time.zone.parse(params[:end_at]).utc ||
      params[:start_at] && (Time.zone.parse(params[:start_at]) + 1.month).utc ||
      Time.zone.now.end_of_month.utc
  end
end

app/controllers/time_tracks_controller.rb
class TimeTracksController < ApplicationController
  before_action :set_time_track, only: %i[show edit update destroy duplicate stop]
  before_action :stop_time, only: %i[start duplicate stop]

  # GET /time_tracks
  # GET /time_tracks.json
  def index
    @time_track = TimeTrack.new
    @date = params[:date] && Time.zone.parse(params[:date]) || Time.zone.now

    start_date = @date.beginning_of_day.utc
    end_date = @date.end_of_day.utc
    @time_tracks = TimeTrack.between(start_date..end_date).all

    render partial: 'table' if params[:refresh]
  end

  def start
    TimeTrack.create(time_track_params.merge(start_at: @new_time))
    redirect_to time_tracks_url
  end

  def duplicate
    TimeTrack.create(@time_track.attributes.slice('description').merge(start_at: @new_time))
    redirect_to time_tracks_url
  end

  def stop
    redirect_to time_tracks_url
  end

  # GET /time_tracks/1
  # GET /time_tracks/1.json
  def show
  end

  # GET /time_tracks/new
  def new
    @time_track = TimeTrack.new
  end

  # GET /time_tracks/1/edit
  def edit
  end

  # POST /time_tracks
  # POST /time_tracks.json
  def create
    @time_track = TimeTrack.new(time_track_params)

    respond_to do |format|
      if @time_track.save
        format.html { redirect_to time_tracks_url, notice: 'Time track was successfully created.' }
        format.json { render :show, status: :created, location: @time_track }
      else
        format.html { render :new }
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_tracks/1
  # PATCH/PUT /time_tracks/1.json
  def update
    respond_to do |format|
      if @time_track.update(time_track_params)
        format.html { redirect_to time_tracks_url, notice: 'Time track was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_track }
      else
        format.html { render :edit }
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tracks/1
  # DELETE /time_tracks/1.json
  def destroy
    @time_track.destroy
    respond_to do |format|
      format.html { redirect_to time_tracks_url, notice: 'Time track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_time_track
    @time_track = TimeTrack.find(params[:id] || params[:time_track_id])
  end

  # Only allow a list of trusted parameters through.
  def time_track_params
    params.require(:time_track).permit(:description, :start_at, :end_at)
  end

  def stop_time
    to_stop = TimeTrack.where(end_at: nil).count.positive?

    if to_stop
      @new_time = Time.current.ceil(5.minutes)
      TimeTrack.where(end_at: nil).update_all(end_at: @new_time)
    else
      @new_time = Time.current.floor(5.minutes)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_tracks_helper.rb
module TimeTracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time Tracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'shared/nav' %>
<div class="container-fluid border">
  <%= yield %>
</div>
</body>
</html>

app/views/report/_date_nav.html.erb
<div class="col-auto">
  <%= link_to bootstrap_icon("arrow-left-square-fill", width: 32, height: 32), report_date_report_index_path(date: @date.to_date - 1.month) %>
  <%= link_to bootstrap_icon("house-fill", width: 32, height: 32), report_date_report_index_path %>
  <%= link_to bootstrap_icon("arrow-right-square-fill", width: 32, height: 32), report_date_report_index_path(date: @date.to_date + 1.month) %>
  <%= link_to bootstrap_icon("cloud-download-fill", width: 32, height: 32), report_date_report_index_path(date: @date.to_date, format: :xlsx) %>
</div>

app/views/report/index.html.erb
<h1>Reports</h1>

<div class="row">
  <%= render 'date_nav' %>
</div>

<div id="reportTableContainer" class="table-responsive">
  <%= render 'table' %>
</div>

app/views/search/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Description</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Current time</th>
  </tr>
  </thead>

  <%
    current_hourly_rate = (ENV.fetch('CURRENT_HOURLY_RATE') { '10' }).to_i
    current_date = nil
    total_date_time = 0.seconds
    total_time = 0.seconds
    @time_tracks.each do |time_track|
      current_time = (time_track.end_at || Time.current) - time_track.start_at
      total_time += current_time
  %>
    <% if current_date && current_date < time_track.start_at&.to_date
         time_set = total_date_time
         total_date_time = current_time
    %>
      <tr>
        <th colspan="2"></th>
        <th>
          $ <%= (current_hourly_rate * time_set / 3600).round(2) %>
        </th>
        <th>
          <%= (time_set / 3600).round(3) %>
        </th>
      </tr>
    <% else
         total_date_time += current_time
    %>
    <% end %>

    <% if !current_date || current_date < time_track.start_at&.to_date
         current_date = time_track.start_at&.to_date
    %>
      <tr>
        <th colspan="4"><%= time_tag(current_date, format: '%F') %></th>
      </tr>
    <% end %>
    <tr>
      <td><%= time_track.description %></td>
      <td><%= time_tag(time_track.start_at, format: '%I:%M%p') %></td>
      <td><%= time_tag(time_track.end_at, format: '%I:%M%p') if time_track.end_at %></td>
      <td><%= Time.at(current_time).utc.strftime("%H:%M:%S") %></td>
    </tr>
  <% end %>
  <% if current_date
       time_set = total_date_time
  %>
    <tr>
      <th colspan="2"></th>
      <th>
        $ <%= (current_hourly_rate * time_set / 3600).round(2) %>
      </th>
      <th>
        <%= (time_set / 3600).round(3) %>
      </th>
    </tr>
  <% end %>
  <tr>
    <th colspan="2">Total</th>
    <th>
      $ <%= current_hourly_rate * (total_time / 3600).round(2) %>
    </th>
    <th>
      <%= (total_time / 3600).round(2) %>
    </th>
  </tr>
</table>

app/views/search/index.html.erb
<h1>Search</h1>
<%= form_with url: search_index_path,method: :get  do |form| %>
<div class="row">
  <div class="col-auto">
    <%= form.datetime_field :start_at, class: "form-control", value: @start_at.in_time_zone.strftime("%Y-%m-%dT%T") %>
  </div>
  <div class="col-auto">
    <%= form.datetime_field :end_at, class: "form-control", value: @end_at.in_time_zone.strftime("%Y-%m-%dT%T") %>
  </div>
  <div class="col-auto">
    <%= form.text_field :q, class: "form-control", value: @q %>
  </div>
  <div class="col-auto">
    <%= form.button 'Search', type: :submit, class: "btn btn-primary", value: @q %>
  </div>
  <div class="col-auto">
    <%= link_to bootstrap_icon("cloud-download-fill", width: 32, height: 32),
                search_index_path(
                  start_at: @start_at,
                  end_at: @end_at,
                  q: @q,
                  format: :xlsx
                ) %>
  </div>
</div>
<% end %>

<div id="reportTableContainer" class="table-responsive">
  <%= render 'table' %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Personal Time Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= time_tracks_path %>">Time Track</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= report_index_path %>">Report</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= search_index_path %>">Search</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/time_tracks/_date_nav.html.erb
<div class="col-auto">
  <%= link_to bootstrap_icon("arrow-left-square-fill", width: 32, height: 32), events_date_time_tracks_path(date: @date.to_date - 1.day) %>
  <%= link_to bootstrap_icon("house-fill", width: 32, height: 32), time_tracks_path %>
  <%#= bootstrap_icon "calendar-date-fill", width: 32, height: 32 %>
  <%= link_to bootstrap_icon("arrow-right-square-fill", width: 32, height: 32), events_date_time_tracks_path(date: @date.to_date + 1.day) %>
</div>

app/views/time_tracks/_form.html.erb
<%= form_with(model: time_track) do |form| %>
  <% if time_track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_track.errors.count, "error") %> prohibited this time_track from being saved:</h2>

      <ul>
        <% time_track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :start_at, class: 'form-label' %>
    <%= form.datetime_field :start_at, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :end_at, class: 'form-label' %>
    <%= form.datetime_field :end_at, class: "form-control" %>
  </div>

  <%= form.button 'Update Time', type: :submit, class: "btn btn-primary" %>
<% end %>

app/views/time_tracks/_start.html.erb
<%= form_with(
      model: time_track,
      url: start_time_tracks_path(time_track),
      method: :post,
      class: 'g-3'
    ) do |form| %>
  <div class="col-6">
    <div class="input-group mb-3">
      <%= form.text_field :description, autocomplete: "off", class: "form-control", placeholder: "Description" %>
      <%= form.button 'Start', type: :submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/time_tracks/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Description</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Current time</th>
    <th>Actions</th>
  </tr>
  </thead>

  <%
    total_time = 0.seconds
    @time_tracks.each do |time_track|
      current_time = (time_track.end_at || Time.current) - time_track.start_at
      total_time += current_time
  %>
    <tr class="table-<%= time_track.end_at.nil? ? 'danger' : 'success' %>">
      <td><%= time_track.description %></td>
      <td><%= time_tag(time_track.start_at, format: '%I:%M%p') %></td>
      <td><%= time_tag(time_track.end_at, format: '%I:%M%p') if time_track.end_at %></td>
      <td class="text-right"><%= Time.at(current_time).utc.strftime("%H:%M:%S") %></td>
      <td>
        <%= link_to bootstrap_icon("pencil-square", width: 20, height: 20), edit_time_track_path(time_track), class: 'btn btn-secondary btn-sm' %>
        <% if !time_track.end_at.nil? %>
          <%= link_to link_to bootstrap_icon("files", width: 20, height: 20), time_track_duplicate_path(time_track), class: 'btn btn-warning btn-sm' %>
        <% else %>
          <%= link_to link_to bootstrap_icon("stop-circle", width: 20, height: 20), time_track_stop_path(time_track), class: 'btn btn-danger btn-sm' %>
        <% end %>
        <%= link_to link_to bootstrap_icon("file-earmark-minus", width: 20, height: 20), time_track, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
      </td>
    </tr>
  <% end %>
  <tr>
    <th colspan="3">Total Time</th>
    <th>
      <%= Time.at(total_time).utc.strftime("%H:%M:%S") %>(<small><%= (total_time / (3600)).round(2) %></small>)
    </th>
    <th></th>
  </tr>
</table>

app/views/time_tracks/edit.html.erb
<h1>Editing Time Track</h1>

<%= render 'form', time_track: @time_track %>

<%= link_to 'Show', @time_track %> |
<%= link_to 'Back', time_tracks_path %>

app/views/time_tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Track</h1>

<div class="row">
  <%= render 'date_nav'%>
</div>

<div class="row">
  <%= render 'start', time_track: @time_track %>
</div>

<div id="timeTrackTableContainer" class="table-responsive">
  <%= render 'table' %>
</div>

<div class="row">
  <div class="col">
    <%= link_to 'Add Time Track', new_time_track_path, class: 'btn btn-dark btn-sm' %>
  </div>
</div>

<%= javascript_pack_tag 'time_track', 'data-turbolinks-track': 'reload' %>

app/views/time_tracks/new.html.erb
<h1>New Time Track</h1>

<%= render 'form', time_track: @time_track %>

<%= link_to 'Back', time_tracks_path %>

app/views/time_tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @time_track.description %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @time_track.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @time_track.end_at %>
</p>

<%= link_to 'Edit', edit_time_track_path(@time_track) %> |
<%= link_to 'Back', time_tracks_path %>